esphome:
  name: muino_water_sensor
  includes:
    - MuinoWaterSensor.h

custom_component:
- lambda: |-
    auto watersensor_sensor = new MuinoWaterSensor();
    App.register_component(watersensor_sensor);
    return {watersensor_sensor};
  components:
  - id: MuinoWaterSensor_id

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
